pipeline {
    agent any

    parameters {
        choice(
            name: 'terraformAction',
            choices: ['apply', 'destroy'],
            description: 'Choose Terraform Action'
        )
    }

    environment {
        ARM_CLIENT_ID       = credentials('ARM_CLIENT_ID')
        ARM_CLIENT_SECRET   = credentials('ARM_CLIENT_SECRET')
        ARM_SUBSCRIPTION_ID = credentials('ARM_SUBSCRIPTION_ID')
        ARM_TENANT_ID       = credentials('ARM_TENANT_ID')
    }

    stages {

        stage('Checkout') {
            steps {
                dir("terraform") {
                    git url: 'https://github.com/Krunal-Dharme/DevSecOps-AI-Powered.git', branch: 'terraform'
                }
            }
        }

        stage('Plan') {
            steps {
                sh 'cd AKS && terraform init'

                sh '''
                    cd AKS && terraform plan -out=tfplan \
                    -var="subscription_id=$ARM_SUBSCRIPTION_ID" \
                    -var="tenant_id=$ARM_TENANT_ID" \
                    -var="client_id=$ARM_CLIENT_ID" \
                    -var="client_secret=$ARM_CLIENT_SECRET"
                '''

                sh 'cd AKS && terraform show -no-color tfplan > tfplan.txt'
            }
        }

        stage('Approval') {
            steps {
                script {
                    def plan = readFile 'AKS/tfplan.txt'

                    input(
                        message: "Approve Terraform Plan?",
                        parameters: [
                            text(
                                name: 'Plan',
                                defaultValue: plan,
                                description: 'Review Terraform Plan'
                            )
                        ]
                    )
                }
            }
        }

        stage('Apply/Destroy') {
            steps {
                script {
                    if (params.terraformAction == 'apply') {
                        sh 'cd AKS && terraform apply -auto-approve tfplan'
                    } else if (params.terraformAction == 'destroy') {
                        sh '''
                            cd AKS && terraform destroy -auto-approve \
                            -var="subscription_id=$ARM_SUBSCRIPTION_ID" \
                            -var="tenant_id=$ARM_TENANT_ID" \
                            -var="client_id=$ARM_CLIENT_ID" \
                            -var="client_secret=$ARM_CLIENT_SECRET"
                        '''
                    }
                }
            }
        }
    }
}
