pipeline {
    agent any

    parameters {
        choice(
            name: 'terraformAction',
            choices: ['apply', 'destroy'],
            description: 'Choose Terraform Action'
        )
    }

    stages {

        stage('Checkout') {
            steps {
                dir("terraform") {
                    git url: 'https://github.com/Krunal-Dharme/DevSecOps-AI-Powered-GCP.git',
                        branch: 'terraform'
                }
            }
        }

        stage('Terraform Init') {
            steps {
                sh '''
                    cd terraform/GKE
                    terraform init
                '''
            }
        }

        stage('Terraform Plan') {
            steps {
                sh '''
                    cd terraform/GKE
                    terraform plan -out=tfplan
                '''

                sh '''
                    cd terraform/GKE
                    terraform show -no-color tfplan > tfplan.txt
                '''
            }
        }

        stage('Approval') {
            steps {
                script {
                    def plan = readFile 'terraform/GKE/tfplan.txt'

                    input(
                        message: "Approve Terraform Plan?",
                        parameters: [
                            text(
                                name: 'Plan',
                                defaultValue: plan,
                                description: 'Review Terraform Plan'
                            )
                        ]
                    )
                }
            }
        }

        stage('Apply/Destroy') {
            steps {
                script {

                    if (params.terraformAction == 'apply') {

                        sh '''
                            cd terraform/GKE
                            terraform apply -auto-approve tfplan
                        '''

                    } else {

                        sh '''
                            cd terraform/GKE
                            terraform destroy -auto-approve
                        '''

                    }
                }
            }
        }

        stage('Configure Kubectl') {
            when {
                expression { params.terraformAction == 'apply' }
            }

            steps {

                sh '''
                    gcloud container clusters get-credentials quantam-gke-new-ai \
                    --zone asia-south1-a \
                    --project my-ai-project-499013
                '''
                sh 'kubectl get nodes'
            }
        }
    }
}
